<?php
declare(strict_types=1);

return [
    'default' => $_ENV['PAYMENT_DEFAULT_GATEWAY'] ?? 'bkash',

    'currency' => $_ENV['PAYMENT_CURRENCY'] ?? 'BDT',

    'gateways' => [
        'bkash' => [
            'name'     => 'bKash',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['BKASH_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['BKASH_SANDBOX_URL'] ?? '',
            'live_url'    => $_ENV['BKASH_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['BKASH_API_KEY'] ?? '',
            'api_secret'  => $_ENV['BKASH_API_SECRET'] ?? '',
        ],
        'rocket' => [
            'name'     => 'Rocket',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['ROCKET_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['ROCKET_SANDBOX_URL'] ?? '',
            'live_url'    => $_ENV['ROCKET_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['ROCKET_API_KEY'] ?? '',
            'api_secret'  => $_ENV['ROCKET_API_SECRET'] ?? '',
        ],
        'nagad' => [
            'name'     => 'Nagad',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['NAGAD_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['NAGAD_SANDBOX_URL'] ?? '',
            'live_url'    => $_ENV['NAGAD_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['NAGAD_API_KEY'] ?? '',
            'api_secret'  => $_ENV['NAGAD_API_SECRET'] ?? '',
        ],
        'uddoktapay' => [
            'name'     => 'UddoktaPay',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['UDDOKTAPAY_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['UDDOKTAPAY_SANDBOX_URL'] ?? 'https://sandbox.uddoktapay.com/api',
            'live_url'    => $_ENV['UDDOKTAPAY_LIVE_URL'] ?? 'https://pay.uddoktapay.com/api',
            'api_key'     => $_ENV['UDDOKTAPAY_API_KEY'] ?? '',
            'refund_payment_method' => $_ENV['UDDOKTAPAY_REFUND_METHOD'] ?? 'bkash',
        ],
        'test_gateway' => [
            'name'     => 'Test / Sandbox',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => true,
            'sandbox_url' => 'local://payments/sandbox',
            'live_url'    => '',
            'api_key'     => '',
            'currency'    => $_ENV['PAYMENT_CURRENCY'] ?? 'BDT',
        ],

        // Extended BD hosted gateways — optional, shipped disabled and served by
        // the config-driven GenericHostedGateway. Draft sandbox URLs: verify
        // against vendor docs before enabling in production.
        'shurjopay' => [
            'name'     => 'ShurjoPay',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['SHURJOPAY_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['SHURJOPAY_SANDBOX_URL'] ?? 'https://sandbox.shurjopay.io/',
            'live_url'    => $_ENV['SHURJOPAY_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['SHURJOPAY_API_KEY'] ?? '',
            'api_secret'  => $_ENV['SHURJOPAY_API_SECRET'] ?? '',
            'currency'    => 'BDT',
            'checkout_method' => 'GET',
            'checkout_url_template' => 'https://sandbox.shurjopay.io/?amount={amount}&currency={currency}&reference={reference}&callback={callback}&cancel={cancel}&api_key={api_key}',
            'verify_url' => 'https://sandbox.shurjopay.io/verify',
            'verify_success_path' => 'status',
            'verify_success_value' => 'COMPLETED',
            'signature_header' => 'X-Webhook-Signature',
        ],
        'portwallet' => [
            'name'     => 'PortWallet',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['PORTWALLET_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['PORTWALLET_SANDBOX_URL'] ?? 'https://sandbox.portwallet.com/cloud-payment/',
            'live_url'    => $_ENV['PORTWALLET_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['PORTWALLET_API_KEY'] ?? '',
            'api_secret'  => $_ENV['PORTWALLET_API_SECRET'] ?? '',
            'currency'    => 'BDT',
            'checkout_method' => 'POST',
            'checkout_url_template' => 'https://sandbox.portwallet.com/cloud-payment/?amount={amount}&currency={currency}&reference={reference}&callback={callback}&cancel={cancel}&api_key={api_key}',
            'verify_url' => 'https://sandbox.portwallet.com/cloud-payment/verify',
            'verify_success_path' => 'status',
            'verify_success_value' => 'COMPLETED',
            'signature_header' => 'X-Webhook-Signature',
        ],
        'cellfin' => [
            'name'     => 'Cellfin',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['CELLFIN_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['CELLFIN_SANDBOX_URL'] ?? 'https://sandbox.cellfin.io',
            'live_url'    => $_ENV['CELLFIN_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['CELLFIN_API_KEY'] ?? '',
            'api_secret'  => $_ENV['CELLFIN_API_SECRET'] ?? '',
            'currency'    => 'BDT',
            'checkout_method' => 'GET',
            'checkout_url_template' => 'https://sandbox.cellfin.io/checkout?amount={amount}&currency={currency}&reference={reference}&callback={callback}&cancel={cancel}&api_key={api_key}',
            'verify_url' => 'https://sandbox.cellfin.io/verify',
            'verify_success_path' => 'status',
            'verify_success_value' => 'COMPLETED',
            'signature_header' => 'X-Webhook-Signature',
        ],
        'purse' => [
            'name'     => 'Purse',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['PURSE_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['PURSE_SANDBOX_URL'] ?? 'https://sandbox.purse.com.bd',
            'live_url'    => $_ENV['PURSE_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['PURSE_API_KEY'] ?? '',
            'api_secret'  => $_ENV['PURSE_API_SECRET'] ?? '',
            'currency'    => 'BDT',
            'checkout_method' => 'GET',
            'checkout_url_template' => 'https://sandbox.purse.com.bd/checkout?amount={amount}&currency={currency}&reference={reference}&callback={callback}&cancel={cancel}&api_key={api_key}',
            'verify_url' => 'https://sandbox.purse.com.bd/verify',
            'verify_success_path' => 'status',
            'verify_success_value' => 'COMPLETED',
            'signature_header' => 'X-Webhook-Signature',
        ],
        'cashby' => [
            'name'     => 'Cashby',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['CASHBY_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['CASHBY_SANDBOX_URL'] ?? 'https://sandbox.cashby.com.bd',
            'live_url'    => $_ENV['CASHBY_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['CASHBY_API_KEY'] ?? '',
            'api_secret'  => $_ENV['CASHBY_API_SECRET'] ?? '',
            'currency'    => 'BDT',
            'checkout_method' => 'GET',
            'checkout_url_template' => 'https://sandbox.cashby.com.bd/checkout?amount={amount}&currency={currency}&reference={reference}&callback={callback}&cancel={cancel}&api_key={api_key}',
            'verify_url' => 'https://sandbox.cashby.com.bd/verify',
            'verify_success_path' => 'status',
            'verify_success_value' => 'COMPLETED',
            'signature_header' => 'X-Webhook-Signature',
        ],
        'upay' => [
            'name'     => 'UPay',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['UPAY_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['UPAY_SANDBOX_URL'] ?? 'https://sandbox.upay.ltd',
            'live_url'    => $_ENV['UPAY_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['UPAY_API_KEY'] ?? '',
            'api_secret'  => $_ENV['UPAY_API_SECRET'] ?? '',
            'currency'    => 'BDT',
            'checkout_method' => 'GET',
            'checkout_url_template' => 'https://sandbox.upay.ltd/checkout?amount={amount}&currency={currency}&reference={reference}&callback={callback}&cancel={cancel}&api_key={api_key}',
            'verify_url' => 'https://sandbox.upay.ltd/verify',
            'verify_success_path' => 'status',
            'verify_success_value' => 'COMPLETED',
            'signature_header' => 'X-Webhook-Signature',
        ],
        'mycash' => [
            'name'     => 'MyCash',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['MYCASH_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['MYCASH_SANDBOX_URL'] ?? 'https://sandbox.mycash.com.bd',
            'live_url'    => $_ENV['MYCASH_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['MYCASH_API_KEY'] ?? '',
            'api_secret'  => $_ENV['MYCASH_API_SECRET'] ?? '',
            'currency'    => 'BDT',
            'checkout_method' => 'GET',
            'checkout_url_template' => 'https://sandbox.mycash.com.bd/checkout?amount={amount}&currency={currency}&reference={reference}&callback={callback}&cancel={cancel}&api_key={api_key}',
            'verify_url' => 'https://sandbox.mycash.com.bd/verify',
            'verify_success_path' => 'status',
            'verify_success_value' => 'COMPLETED',
            'signature_header' => 'X-Webhook-Signature',
        ],
        'payer' => [
            'name'     => 'Payer',
            'type'     => 'mobile_financial_service',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['PAYER_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['PAYER_SANDBOX_URL'] ?? 'https://sandbox.payer.com.bd',
            'live_url'    => $_ENV['PAYER_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['PAYER_API_KEY'] ?? '',
            'api_secret'  => $_ENV['PAYER_API_SECRET'] ?? '',
            'currency'    => 'BDT',
            'checkout_method' => 'GET',
            'checkout_url_template' => 'https://sandbox.payer.com.bd/checkout?amount={amount}&currency={currency}&reference={reference}&callback={callback}&cancel={cancel}&api_key={api_key}',
            'verify_url' => 'https://sandbox.payer.com.bd/verify',
            'verify_success_path' => 'status',
            'verify_success_value' => 'COMPLETED',
            'signature_header' => 'X-Webhook-Signature',
        ],
        'stripe' => [
            'name'     => 'Stripe',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['STRIPE_TEST_MODE'] ?? 'true') === 'true',
            'api_key'     => $_ENV['STRIPE_SECRET_KEY'] ?? '',
            'publishable' => $_ENV['STRIPE_PUBLISHABLE_KEY'] ?? '',
            'webhook_secret' => $_ENV['STRIPE_WEBHOOK_SECRET'] ?? '',
        ],
        'paypal' => [
            'name'     => 'PayPal',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['PAYPAL_TEST_MODE'] ?? 'true') === 'true',
            'client_id'     => $_ENV['PAYPAL_CLIENT_ID'] ?? '',
            'client_secret' => $_ENV['PAYPAL_CLIENT_SECRET'] ?? '',
            'mode'          => $_ENV['PAYPAL_MODE'] ?? 'sandbox',
        ],
        'paddle' => [
            'name'     => 'Paddle',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['PADDLE_TEST_MODE'] ?? 'true') === 'true',
            'vendor_id' => $_ENV['PADDLE_VENDOR_ID'] ?? '',
            'vendor_auth_code' => $_ENV['PADDLE_VENDOR_AUTH_CODE'] ?? '',
        ],

        // International gateways — optional, shipped disabled. Served by the
        // config-driven GenericHostedGateway; these are config fallbacks only
        // (runtime credentials live in the payment_gateways table).
        'gpay' => [
            'name'     => 'Google Pay',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['GPAY_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['GPAY_SANDBOX_URL'] ?? '',
            'live_url'    => $_ENV['GPAY_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['GPAY_API_KEY'] ?? '',
            'api_secret'  => $_ENV['GPAY_API_SECRET'] ?? '',
            'currency'    => $_ENV['GPAY_CURRENCY'] ?? 'USD',
        ],
        'applepay' => [
            'name'     => 'Apple Pay',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['APPLEPAY_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['APPLEPAY_SANDBOX_URL'] ?? '',
            'live_url'    => $_ENV['APPLEPAY_LIVE_URL'] ?? '',
            'api_key'     => $_ENV['APPLEPAY_API_KEY'] ?? '',
            'api_secret'  => $_ENV['APPLEPAY_API_SECRET'] ?? '',
            'currency'    => $_ENV['APPLEPAY_CURRENCY'] ?? 'USD',
        ],
        'razorpay' => [
            'name'     => 'Razorpay',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['RAZORPAY_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['RAZORPAY_SANDBOX_URL'] ?? 'https://api.razorpay.com/v1',
            'live_url'    => $_ENV['RAZORPAY_LIVE_URL'] ?? 'https://api.razorpay.com/v1',
            'api_key'     => $_ENV['RAZORPAY_KEY_ID'] ?? '',
            'api_secret'  => $_ENV['RAZORPAY_KEY_SECRET'] ?? '',
            'currency'    => $_ENV['RAZORPAY_CURRENCY'] ?? 'INR',
        ],
        'paystack' => [
            'name'     => 'Paystack',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['PAYSTACK_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['PAYSTACK_SANDBOX_URL'] ?? 'https://api.paystack.co',
            'live_url'    => $_ENV['PAYSTACK_LIVE_URL'] ?? 'https://api.paystack.co',
            'api_key'     => $_ENV['PAYSTACK_SECRET_KEY'] ?? '',
            'api_secret'  => $_ENV['PAYSTACK_PUBLIC_KEY'] ?? '',
            'currency'    => $_ENV['PAYSTACK_CURRENCY'] ?? 'NGN',
        ],
        'flutterwave' => [
            'name'     => 'Flutterwave',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['FLUTTERWAVE_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['FLUTTERWAVE_SANDBOX_URL'] ?? 'https://api.flutterwave.com/v3',
            'live_url'    => $_ENV['FLUTTERWAVE_LIVE_URL'] ?? 'https://api.flutterwave.com/v3',
            'api_key'     => $_ENV['FLUTTERWAVE_PUBLIC_KEY'] ?? '',
            'api_secret'  => $_ENV['FLUTTERWAVE_SECRET_KEY'] ?? '',
            'currency'    => $_ENV['FLUTTERWAVE_CURRENCY'] ?? 'NGN',
        ],
        'sslcommerz' => [
            'name'     => 'SSLCommerz',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['SSLCOMMERZ_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['SSLCOMMERZ_SANDBOX_URL'] ?? 'https://sandbox.sslcommerz.com/gwprocess/v4/api.php',
            'live_url'    => $_ENV['SSLCOMMERZ_LIVE_URL'] ?? 'https://securepay.sslcommerz.com/gwprocess/v4/api.php',
            'api_key'     => $_ENV['SSLCOMMERZ_STORE_ID'] ?? '',
            'api_secret'  => $_ENV['SSLCOMMERZ_STORE_PASSWORD'] ?? '',
            'currency'    => $_ENV['SSLCOMMERZ_CURRENCY'] ?? 'BDT',
        ],
        'square' => [
            'name'     => 'Square',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['SQUARE_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['SQUARE_SANDBOX_URL'] ?? 'https://connect.squareupsandbox.com',
            'live_url'    => $_ENV['SQUARE_LIVE_URL'] ?? 'https://connect.squareup.com',
            'api_key'     => $_ENV['SQUARE_ACCESS_TOKEN'] ?? '',
            'api_secret'  => $_ENV['SQUARE_APPLICATION_ID'] ?? '',
            'currency'    => $_ENV['SQUARE_CURRENCY'] ?? 'USD',
        ],
        'mollie' => [
            'name'     => 'Mollie',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['MOLLIE_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['MOLLIE_SANDBOX_URL'] ?? 'https://api.mollie.com/v2',
            'live_url'    => $_ENV['MOLLIE_LIVE_URL'] ?? 'https://api.mollie.com/v2',
            'api_key'     => $_ENV['MOLLIE_API_KEY'] ?? '',
            'currency'    => $_ENV['MOLLIE_CURRENCY'] ?? 'EUR',
        ],
        'authorize_net' => [
            'name'     => 'Authorize.Net',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['AUTHORIZE_NET_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['AUTHORIZE_NET_SANDBOX_URL'] ?? 'https://apitest.authorize.net/xml/v1/request.api',
            'live_url'    => $_ENV['AUTHORIZE_NET_LIVE_URL'] ?? 'https://api.authorize.net/xml/v1/request.api',
            'api_key'     => $_ENV['AUTHORIZE_NET_API_LOGIN_ID'] ?? '',
            'api_secret'  => $_ENV['AUTHORIZE_NET_TRANSACTION_KEY'] ?? '',
            'currency'    => $_ENV['AUTHORIZE_NET_CURRENCY'] ?? 'USD',
        ],
        'xendit' => [
            'name'     => 'Xendit',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['XENDIT_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['XENDIT_SANDBOX_URL'] ?? 'https://api.xendit.co',
            'live_url'    => $_ENV['XENDIT_LIVE_URL'] ?? 'https://api.xendit.co',
            'api_key'     => $_ENV['XENDIT_SECRET_KEY'] ?? '',
            'currency'    => $_ENV['XENDIT_CURRENCY'] ?? 'IDR',
        ],
        'adyen' => [
            'name'     => 'Adyen',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['ADYEN_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['ADYEN_SANDBOX_URL'] ?? 'https://checkout-test.adyen.com/v71',
            'live_url'    => $_ENV['ADYEN_LIVE_URL'] ?? 'https://checkout-live.adyen.com/v71',
            'api_key'     => $_ENV['ADYEN_API_KEY'] ?? '',
            'api_secret'  => $_ENV['ADYEN_MERCHANT_ACCOUNT'] ?? '',
            'currency'    => $_ENV['ADYEN_CURRENCY'] ?? 'EUR',
        ],
        'skrill' => [
            'name'     => 'Skrill',
            'type'     => 'online_payment',
            'is_online' => true,
            'has_api'   => true,
            'test_mode' => ($_ENV['SKRILL_TEST_MODE'] ?? 'true') === 'true',
            'sandbox_url' => $_ENV['SKRILL_SANDBOX_URL'] ?? 'https://pay.sandbox.skrill.com/app/pay.pl',
            'live_url'    => $_ENV['SKRILL_LIVE_URL'] ?? 'https://pay.skrill.com/app/pay.pl',
            'api_key'     => $_ENV['SKRILL_MERCHANT_EMAIL'] ?? '',
            'api_secret'  => $_ENV['SKRILL_SECRET_WORD'] ?? '',
            'currency'    => $_ENV['SKRILL_CURRENCY'] ?? 'USD',
        ],
    ],

    'offline' => [
        'bank_name'   => $_ENV['OFFLINE_BANK_NAME'] ?? '',
        'account_name' => $_ENV['OFFLINE_ACCOUNT_NAME'] ?? '',
        'account_number' => $_ENV['OFFLINE_ACCOUNT_NUMBER'] ?? '',
        'routing_number' => $_ENV['OFFLINE_ROUTING_NUMBER'] ?? '',
        'instructions'   => $_ENV['OFFLINE_INSTRUCTIONS'] ?? '',
    ],
];
