<?php

namespace Database\Seeders;

use App\Models\PaymentGateway;
use Illuminate\Database\Seeder;

class PaymentGatewaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gateways = [
            // bKash - Mobile Financial Service
            [
                'name' => 'bKash',
                'code' => 'bkash',
                'type' => 'mobile_financial_service',
                'is_active' => true,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => 'test_api_key',
                'api_secret' => 'test_api_secret',
                'username' => 'test_username',
                'password' => 'test_password',
                'sandbox_url' => 'https://tokenized.sandbox.bka.sh/v1.2.0-beta/tokenized',
                'live_url' => 'https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized',
                'callback_url' => url('/api/payments/bkash/callback'),
                'webhook_url' => url('/api/payments/bkash/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/bkash/ipn'),
                'logo' => 'gateways/bkash.png',
                'description' => 'bKash is a leading mobile financial service in Bangladesh',
                'instructions' => '1. Dial *247# to open bKash menu\n2. Select "Payment"\n3. Enter Merchant bKash Account: 017XXXXXXXX\n4. Enter Amount\n5. Enter Reference: Your Invoice Number\n6. Enter Counter: 1\n7. Enter your bKash Mobile Menu PIN to confirm',
                'currency' => 'BDT',
                'fee_percentage' => 1.85,
                'fee_fixed' => 10,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 1,
            ],
            // Nagad - Mobile Financial Service
            [
                'name' => 'Nagad',
                'code' => 'nagad',
                'type' => 'mobile_financial_service',
                'is_active' => true,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => 'test_api_key',
                'api_secret' => 'test_api_secret',
                'sandbox_url' => 'https://sandbox.mynagad.com:10080/remote-payment-gateway-1.0/api/dfs',
                'live_url' => 'https://api.mynagad.com/api/dfs',
                'callback_url' => url('/api/payments/nagad/callback'),
                'webhook_url' => url('/api/payments/nagad/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/nagad/ipn'),
                'logo' => 'gateways/nagad.png',
                'description' => 'Nagad is a leading mobile financial service in Bangladesh',
                'instructions' => '1. Dial *167# to open Nagad menu\n2. Select "Payment"\n3. Enter Merchant Nagad Account: 017XXXXXXXX\n4. Enter Amount\n5. Enter Reference: Your Invoice Number\n6. Enter your Nagad Mobile Menu PIN to confirm',
                'currency' => 'BDT',
                'fee_percentage' => 1.4,
                'fee_fixed' => 10,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 2,
            ],
            // Rocket - Mobile Financial Service
            [
                'name' => 'Rocket',
                'code' => 'rocket',
                'type' => 'mobile_financial_service',
                'is_active' => true,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => 'test_api_key',
                'api_secret' => 'test_api_secret',
                'sandbox_url' => 'https://sandbox.rocket.com.bd/api/v1',
                'live_url' => 'https://api.rocket.com.bd/api/v1',
                'callback_url' => url('/api/payments/rocket/callback'),
                'webhook_url' => url('/api/payments/rocket/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/rocket/ipn'),
                'logo' => 'gateways/rocket.png',
                'description' => 'Rocket is a mobile financial service by Dutch-Bangla Bank',
                'instructions' => '1. Dial *322# to open Rocket menu\n2. Select "Payment"\n3. Enter Biller ID: SCHOOL\n4. Enter Bill Number: Your Invoice Number\n5. Enter Amount\n6. Enter your Rocket Mobile Menu PIN to confirm',
                'currency' => 'BDT',
                'fee_percentage' => 1.2,
                'fee_fixed' => 10,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 3,
            ],
            // UddoktaPay - Bangladeshi aggregator (bKash/Nagad/Rocket/Upay/Bank)
            // Disabled by default: enable it from Dashboard > Settings > Payment.
            [
                'name' => 'UddoktaPay',
                'code' => 'uddoktapay',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.uddoktapay.com/api',
                'live_url' => 'https://pay.uddoktapay.com/api',
                'callback_url' => url('/api/payments/uddoktapay/callback'),
                'webhook_url' => url('/api/payments/uddoktapay/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/uddoktapay/webhook'),
                'logo' => 'gateways/uddoktapay.png',
                'description' => 'UddoktaPay aggregates bKash, Nagad, Rocket, Upay and bank transfers in one checkout',
                'instructions' => 'You will be redirected to the UddoktaPay hosted checkout to pay with bKash, Nagad, Rocket, Upay or bank transfer.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 4,
            ],
            // Test / Sandbox - local gateway, zero credentials, never moves money
            [
                'name' => 'Test / Sandbox',
                'code' => 'test_gateway',
                'type' => 'online_payment',
                'is_active' => true,
                'is_online' => true,
                'has_api' => false,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => null,
                'live_url' => null,
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Free test gateway: run the full payment flow locally without moving money',
                'instructions' => 'You will be redirected to the local sandbox page where you can simulate a successful, failed or cancelled payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 1,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT', 'USD'],
                'sort_order' => 5,
            ],
            // --- Extended BD hosted gateways (config-driven GenericHostedGatewayAdapter) ---
            // DRAFT rows: sandbox/live URLs and extra_attributes endpoints are
            // unverified placeholders — confirm them against each provider's
            // official documentation before enabling a gateway. All ship
            // disabled with empty credentials, exactly like UddoktaPay.

            // ShurjoPay
            [
                'name' => 'ShurjoPay',
                'code' => 'shurjopay',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.shurjopay.io/',
                'live_url' => 'https://payment.shurjohub.com/',
                'callback_url' => url('/api/payments/shurjopay/callback'),
                'webhook_url' => url('/api/payments/shurjopay/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/shurjopay/webhook'),
                'description' => 'ShurjoPay hosted checkout for bKash, Nagad, Rocket, UPay and cards',
                'instructions' => 'You will be redirected to the ShurjoPay hosted checkout to complete payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 32,
                'extra_attributes' => [
                    'checkout_method' => 'GET',
                    'checkout_url_template' => 'https://sandbox.shurjopay.io/checkout?amount={amount}&currency={currency}&reference={reference}&invoice={invoice}&callback={callback}&cancel={cancel}&api_key={api_key}',
                    'verify_url' => 'https://sandbox.shurjopay.io/verify',
                    'verify_success_path' => 'status',
                    'verify_success_value' => 'COMPLETED',
                ],
            ],
            // PortWallet
            [
                'name' => 'PortWallet',
                'code' => 'portwallet',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.portwallet.com/cloud-payment/',
                'live_url' => null,
                'callback_url' => url('/api/payments/portwallet/callback'),
                'webhook_url' => url('/api/payments/portwallet/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/portwallet/webhook'),
                'description' => 'PortWallet hosted checkout for cards and mobile financial services',
                'instructions' => 'You will be redirected to the PortWallet hosted checkout to complete payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 33,
                'extra_attributes' => [
                    'checkout_method' => 'GET',
                    'checkout_url_template' => 'https://sandbox.portwallet.com/cloud-payment/?amount={amount}&currency={currency}&reference={reference}&invoice={invoice}&callback={callback}&cancel={cancel}&api_key={api_key}',
                    'verify_url' => 'https://sandbox.portwallet.com/cloud-payment/verify',
                    'verify_success_path' => 'status',
                    'verify_success_value' => 'COMPLETED',
                ],
            ],
            // Cellfin
            [
                'name' => 'Cellfin',
                'code' => 'cellfin',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.cellfin.io',
                'live_url' => null,
                'callback_url' => url('/api/payments/cellfin/callback'),
                'webhook_url' => url('/api/payments/cellfin/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/cellfin/webhook'),
                'description' => 'Cellfin bank and wallet aggregator checkout',
                'instructions' => 'You will be redirected to the Cellfin hosted checkout to complete payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 34,
                'extra_attributes' => [
                    'checkout_method' => 'GET',
                    'checkout_url_template' => 'https://sandbox.cellfin.io/checkout?amount={amount}&currency={currency}&reference={reference}&invoice={invoice}&callback={callback}&cancel={cancel}&api_key={api_key}',
                    'verify_url' => 'https://sandbox.cellfin.io/verify',
                    'verify_success_path' => 'status',
                    'verify_success_value' => 'COMPLETED',
                ],
            ],
            // Purse
            [
                'name' => 'Purse',
                'code' => 'purse',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.purse.com.bd',
                'live_url' => null,
                'callback_url' => url('/api/payments/purse/callback'),
                'webhook_url' => url('/api/payments/purse/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/purse/webhook'),
                'description' => 'Purse mobile financial services aggregator checkout',
                'instructions' => 'You will be redirected to the Purse hosted checkout to complete payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 35,
                'extra_attributes' => [
                    'checkout_method' => 'GET',
                    'checkout_url_template' => 'https://sandbox.purse.com.bd/checkout?amount={amount}&currency={currency}&reference={reference}&invoice={invoice}&callback={callback}&cancel={cancel}&api_key={api_key}',
                    'verify_url' => 'https://sandbox.purse.com.bd/verify',
                    'verify_success_path' => 'status',
                    'verify_success_value' => 'COMPLETED',
                ],
            ],
            // Cashby
            [
                'name' => 'Cashby',
                'code' => 'cashby',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.cashby.com.bd',
                'live_url' => null,
                'callback_url' => url('/api/payments/cashby/callback'),
                'webhook_url' => url('/api/payments/cashby/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/cashby/webhook'),
                'description' => 'Cashby merchant checkout and payout gateway',
                'instructions' => 'You will be redirected to the Cashby hosted checkout to complete payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 36,
                'extra_attributes' => [
                    'checkout_method' => 'GET',
                    'checkout_url_template' => 'https://sandbox.cashby.com.bd/checkout?amount={amount}&currency={currency}&reference={reference}&invoice={invoice}&callback={callback}&cancel={cancel}&api_key={api_key}',
                    'verify_url' => 'https://sandbox.cashby.com.bd/verify',
                    'verify_success_path' => 'status',
                    'verify_success_value' => 'COMPLETED',
                ],
            ],
            // UPay
            [
                'name' => 'UPay',
                'code' => 'upay',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.upay.ltd',
                'live_url' => null,
                'callback_url' => url('/api/payments/upay/callback'),
                'webhook_url' => url('/api/payments/upay/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/upay/webhook'),
                'description' => 'UPay (Trust Axiata Pay) mobile financial services checkout',
                'instructions' => 'You will be redirected to the UPay hosted checkout to complete payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 37,
                'extra_attributes' => [
                    'checkout_method' => 'GET',
                    'checkout_url_template' => 'https://sandbox.upay.ltd/checkout?amount={amount}&currency={currency}&reference={reference}&invoice={invoice}&callback={callback}&cancel={cancel}&api_key={api_key}',
                    'verify_url' => 'https://sandbox.upay.ltd/verify',
                    'verify_success_path' => 'status',
                    'verify_success_value' => 'COMPLETED',
                ],
            ],
            // MyCash
            [
                'name' => 'MyCash',
                'code' => 'mycash',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.mycash.com.bd',
                'live_url' => null,
                'callback_url' => url('/api/payments/mycash/callback'),
                'webhook_url' => url('/api/payments/mycash/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/mycash/webhook'),
                'description' => 'MyCash mobile financial services aggregator checkout',
                'instructions' => 'You will be redirected to the MyCash hosted checkout to complete payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 38,
                'extra_attributes' => [
                    'checkout_method' => 'GET',
                    'checkout_url_template' => 'https://sandbox.mycash.com.bd/checkout?amount={amount}&currency={currency}&reference={reference}&invoice={invoice}&callback={callback}&cancel={cancel}&api_key={api_key}',
                    'verify_url' => 'https://sandbox.mycash.com.bd/verify',
                    'verify_success_path' => 'status',
                    'verify_success_value' => 'COMPLETED',
                ],
            ],
            // Payer
            [
                'name' => 'Payer',
                'code' => 'payer',
                'type' => 'mobile_financial_service',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'api_key' => null,
                'sandbox_url' => 'https://sandbox.payer.com.bd',
                'live_url' => null,
                'callback_url' => url('/api/payments/payer/callback'),
                'webhook_url' => url('/api/payments/payer/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'ipn_url' => url('/api/payments/payer/webhook'),
                'description' => 'Payer merchant gateway hosted checkout',
                'instructions' => 'You will be redirected to the Payer hosted checkout to complete payment.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'min_amount' => 10,
                'max_amount' => 50000,
                'supported_currencies' => ['BDT'],
                'sort_order' => 39,
                'extra_attributes' => [
                    'checkout_method' => 'GET',
                    'checkout_url_template' => 'https://sandbox.payer.com.bd/checkout?amount={amount}&currency={currency}&reference={reference}&invoice={invoice}&callback={callback}&cancel={cancel}&api_key={api_key}',
                    'verify_url' => 'https://sandbox.payer.com.bd/verify',
                    'verify_success_path' => 'status',
                    'verify_success_value' => 'COMPLETED',
                ],
            ],
            // --- International gateways (optional; disabled until enabled) ---

            // Google Pay
            [
                'name' => 'Google Pay',
                'code' => 'gpay',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => null,
                'live_url' => null,
                'callback_url' => url('/api/payments/gpay/callback'),
                'webhook_url' => url('/api/payments/gpay/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Google Pay — pay with cards saved to a Google account',
                'instructions' => 'You will be redirected to the Google Pay hosted checkout. Supply your merchant checkout endpoint and key to enable it.',
                'currency' => 'USD',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'INR', 'SGD', 'AUD', 'CAD'],
                'min_amount' => 1,
                'sort_order' => 20,
            ],
            // Apple Pay
            [
                'name' => 'Apple Pay',
                'code' => 'applepay',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => null,
                'live_url' => null,
                'callback_url' => url('/api/payments/applepay/callback'),
                'webhook_url' => url('/api/payments/applepay/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Apple Pay — pay with cards saved to an Apple Wallet',
                'instructions' => 'You will be redirected to the Apple Pay hosted checkout. Supply your merchant checkout endpoint and key to enable it.',
                'currency' => 'USD',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'SGD'],
                'min_amount' => 1,
                'sort_order' => 21,
            ],
            // Razorpay
            [
                'name' => 'Razorpay',
                'code' => 'razorpay',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://api.razorpay.com/v1',
                'live_url' => 'https://api.razorpay.com/v1',
                'callback_url' => url('/api/payments/razorpay/callback'),
                'webhook_url' => url('/api/payments/razorpay/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Razorpay — cards, UPI, netbanking and wallets (India and international)',
                'instructions' => 'You will be redirected to the Razorpay hosted checkout to complete payment.',
                'currency' => 'INR',
                'supported_currencies' => ['INR', 'USD'],
                'min_amount' => 1,
                'sort_order' => 22,
            ],
            // Paystack
            [
                'name' => 'Paystack',
                'code' => 'paystack',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://api.paystack.co',
                'live_url' => 'https://api.paystack.co',
                'callback_url' => url('/api/payments/paystack/callback'),
                'webhook_url' => url('/api/payments/paystack/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Paystack — cards, bank transfer and mobile money across Africa',
                'instructions' => 'You will be redirected to the Paystack hosted checkout to complete payment.',
                'currency' => 'NGN',
                'supported_currencies' => ['NGN', 'GHS', 'ZAR', 'KES', 'USD'],
                'min_amount' => 1,
                'sort_order' => 23,
            ],
            // Flutterwave
            [
                'name' => 'Flutterwave',
                'code' => 'flutterwave',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://api.flutterwave.com/v3',
                'live_url' => 'https://api.flutterwave.com/v3',
                'callback_url' => url('/api/payments/flutterwave/callback'),
                'webhook_url' => url('/api/payments/flutterwave/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Flutterwave — cards, mobile money and bank transfers across Africa',
                'instructions' => 'You will be redirected to the Flutterwave hosted checkout to complete payment.',
                'currency' => 'NGN',
                'supported_currencies' => ['NGN', 'GHS', 'KES', 'ZAR', 'USD', 'EUR', 'GBP'],
                'min_amount' => 1,
                'sort_order' => 24,
            ],
            // SSLCommerz
            [
                'name' => 'SSLCommerz',
                'code' => 'sslcommerz',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://sandbox.sslcommerz.com/gwprocess/v4/api.php',
                'live_url' => 'https://securepay.sslcommerz.com/gwprocess/v4/api.php',
                'callback_url' => url('/api/payments/sslcommerz/callback'),
                'webhook_url' => url('/api/payments/sslcommerz/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'SSLCommerz — cards, mobile banking and internet banking (Bangladesh and international)',
                'instructions' => 'You will be redirected to the SSLCommerz hosted checkout to complete payment.',
                'currency' => 'BDT',
                'supported_currencies' => ['BDT', 'USD', 'EUR', 'GBP', 'INR'],
                'min_amount' => 1,
                'sort_order' => 25,
            ],
            // Square
            [
                'name' => 'Square',
                'code' => 'square',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://connect.squareupsandbox.com',
                'live_url' => 'https://connect.squareup.com',
                'callback_url' => url('/api/payments/square/callback'),
                'webhook_url' => url('/api/payments/square/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Square — cards and digital wallets',
                'instructions' => 'You will be redirected to the Square hosted checkout to complete payment.',
                'currency' => 'USD',
                'supported_currencies' => ['USD', 'CAD', 'GBP', 'AUD', 'JPY', 'EUR'],
                'min_amount' => 1,
                'sort_order' => 26,
            ],
            // Mollie
            [
                'name' => 'Mollie',
                'code' => 'mollie',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://api.mollie.com/v2',
                'live_url' => 'https://api.mollie.com/v2',
                'callback_url' => url('/api/payments/mollie/callback'),
                'webhook_url' => url('/api/payments/mollie/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Mollie — cards, iDEAL, Bancontact, SEPA and more across Europe',
                'instructions' => 'You will be redirected to the Mollie hosted checkout to complete payment.',
                'currency' => 'EUR',
                'supported_currencies' => ['EUR', 'USD', 'GBP', 'CHF', 'SEK', 'NOK', 'DKK', 'PLN'],
                'min_amount' => 1,
                'sort_order' => 27,
            ],
            // Authorize.Net
            [
                'name' => 'Authorize.Net',
                'code' => 'authorize_net',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://apitest.authorize.net/xml/v1/request.api',
                'live_url' => 'https://api.authorize.net/xml/v1/request.api',
                'callback_url' => url('/api/payments/authorize_net/callback'),
                'webhook_url' => url('/api/payments/authorize_net/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Authorize.Net — card payments and e-checks',
                'instructions' => 'You will be redirected to the Authorize.Net hosted checkout to complete payment.',
                'currency' => 'USD',
                'supported_currencies' => ['USD', 'CAD', 'GBP', 'EUR', 'AUD'],
                'min_amount' => 1,
                'sort_order' => 28,
            ],
            // Xendit
            [
                'name' => 'Xendit',
                'code' => 'xendit',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://api.xendit.co',
                'live_url' => 'https://api.xendit.co',
                'callback_url' => url('/api/payments/xendit/callback'),
                'webhook_url' => url('/api/payments/xendit/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Xendit — cards, e-wallets, bank transfers and retail outlets across Southeast Asia',
                'instructions' => 'You will be redirected to the Xendit hosted checkout to complete payment.',
                'currency' => 'IDR',
                'supported_currencies' => ['IDR', 'PHP', 'THB', 'VND', 'MYR', 'SGD', 'USD'],
                'min_amount' => 1,
                'sort_order' => 29,
            ],
            // Adyen
            [
                'name' => 'Adyen',
                'code' => 'adyen',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://checkout-test.adyen.com/v71',
                'live_url' => 'https://checkout-live.adyen.com/v71',
                'callback_url' => url('/api/payments/adyen/callback'),
                'webhook_url' => url('/api/payments/adyen/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Adyen — cards, wallets and local payment methods worldwide',
                'instructions' => 'You will be redirected to the Adyen hosted checkout to complete payment.',
                'currency' => 'EUR',
                'supported_currencies' => ['EUR', 'USD', 'GBP', 'AUD', 'CAD', 'JPY', 'SGD', 'INR'],
                'min_amount' => 1,
                'sort_order' => 30,
            ],
            // Skrill
            [
                'name' => 'Skrill',
                'code' => 'skrill',
                'type' => 'online_payment',
                'is_active' => false,
                'is_online' => true,
                'has_api' => true,
                'test_mode' => true,
                'sandbox_url' => 'https://pay.sandbox.skrill.com/app/pay.pl',
                'live_url' => 'https://pay.skrill.com/app/pay.pl',
                'callback_url' => url('/api/payments/skrill/callback'),
                'webhook_url' => url('/api/payments/skrill/webhook'),
                'success_url' => url('/payments/success'),
                'cancel_url' => url('/payments/cancel'),
                'description' => 'Skrill — digital wallet and card payments',
                'instructions' => 'You will be redirected to the Skrill hosted checkout to complete payment.',
                'currency' => 'USD',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'JPY'],
                'min_amount' => 1,
                'sort_order' => 31,
            ],
            // Cash - Offline Payment
            [
                'name' => 'Cash',
                'code' => 'cash',
                'type' => 'other',
                'is_active' => true,
                'is_online' => false,
                'has_api' => false,
                'description' => 'Pay with cash at the school office',
                'instructions' => 'Please visit the school office to make a cash payment during office hours.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'sort_order' => 10,
            ],
            // Bank Transfer - Offline Payment
            [
                'name' => 'Bank Transfer',
                'code' => 'bank_transfer',
                'type' => 'bank',
                'is_active' => true,
                'is_online' => false,
                'has_api' => false,
                'description' => 'Transfer money directly to our bank account',
                'instructions' => "Bank Name: Example Bank\nAccount Name: Your School Name\nAccount Number: 1234567890123\nBranch: Main Branch\nRouting Number: 123456789\n\nPlease include your invoice number as the payment reference.",
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'sort_order' => 11,
            ],
            // Cheque - Offline Payment
            [
                'name' => 'Cheque',
                'code' => 'cheque',
                'type' => 'bank',
                'is_active' => true,
                'is_online' => false,
                'has_api' => false,
                'description' => 'Pay by cheque at the school office',
                'instructions' => 'Please make the cheque payable to "Your School Name" and submit it to the school office during office hours. Include your invoice number on the back of the cheque.',
                'currency' => 'BDT',
                'fee_percentage' => 0,
                'fee_fixed' => 0,
                'sort_order' => 12,
            ],
        ];

        foreach ($gateways as $gateway) {
            // Extract extra attributes that are not direct columns
            $extraAttributes = [];
            $columns = [
                'name', 'code', 'type', 'is_active', 'is_online', 'has_api', 'test_mode',
                'api_key', 'api_secret', 'api_username', 'api_password', 'sandbox_url', 'live_url',
                'callback_url', 'webhook_url', 'success_url', 'cancel_url', 'ipn_url', 'logo',
                'description', 'instructions', 'currency', 'fee_percentage', 'fee_fixed',
                'min_amount', 'max_amount', 'supported_currencies', 'sort_order', 'extra_attributes',
            ];

            foreach ($gateway as $key => $value) {
                if (! in_array($key, $columns)) {
                    $extraAttributes[$key] = $value;
                    unset($gateway[$key]);
                }
            }

            // Add extra attributes to the gateway
            if (! empty($extraAttributes)) {
                $gateway['extra_attributes'] = $extraAttributes;
            }

            // Create or update the gateway
            PaymentGateway::updateOrCreate(
                ['code' => $gateway['code']],
                $gateway
            );
        }

        $this->command->info('Payment gateways seeded successfully!');
    }
}
