@extends('layouts.dashboard')
@section('title', __('Certificate') . ' — ' . config('app.name'))
@section('content')
<div class="mb-6 flex items-center justify-between">
    <h1 class="text-2xl font-bold text-gray-900">{{ __('Certificate') }}: {{ $certificate->certificate_number }}</h1>
    <div class="flex gap-2">
        <a href="{{ route('dashboard.certificates.index') }}" class="rounded-lg bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-200">{{ __('Back') }}</a>
        <a href="{{ route('dashboard.certificates.print', $certificate) }}" target="_blank" class="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700">{{ __('Print') }}</a>
        @can('update', $certificate)
            <a href="{{ route('dashboard.certificates.edit', $certificate) }}" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700">{{ __('Edit') }}</a>
        @endcan
        @can('delete', $certificate)
            <form method="post" action="{{ route('dashboard.certificates.destroy', $certificate) }}" onsubmit="return confirm('{{ __('Are you sure?') }}')">
                @csrf @method('delete')
                <button type="submit" class="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700">{{ __('Delete') }}</button>
            </form>
        @endcan
    </div>
</div>
<div class="grid gap-6 sm:grid-cols-2">
    <div class="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
        <dl class="space-y-4 text-sm">
            <div><dt class="text-gray-500">{{ __('Certificate number') }}</dt><dd class="font-mono font-medium">{{ $certificate->certificate_number }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Student') }}</dt><dd class="font-medium">{{ $certificate->student?->user?->name ?? 'N/A' }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Type') }}</dt><dd><span class="rounded-full bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-700">{{ __(ucfirst($certificate->certificate_type)) }}</span></dd></div>
            <div><dt class="text-gray-500">{{ __('Issue date') }}</dt><dd>{{ $certificate->issue_date?->format('d M Y') }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Status') }}</dt><dd><span class="rounded-full px-2.5 py-0.5 text-xs font-medium {{ $certificate->status === 'issued' ? 'bg-green-100 text-green-700' : ($certificate->status === 'revoked' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700') }}">{{ __(ucfirst($certificate->status)) }}</span></dd></div>
            <div><dt class="text-gray-500">{{ __('Generated by') }}</dt><dd>{{ $certificate->generatedBy?->name ?? 'N/A' }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Created') }}</dt><dd>{{ $certificate->created_at?->format('d M Y H:i') }}</dd></div>
            @if(!empty($certificate->body))
                <div class="sm:col-span-2"><dt class="text-gray-500">{{ __('Certificate body') }}</dt><dd class="mt-1 whitespace-pre-wrap text-sm text-gray-700">{{ is_array($certificate->body) ? implode("\n", $certificate->body) : $certificate->body }}</dd></div>
            @endif
        </dl>
    </div>
</div>
@endsection