@extends('layouts.dashboard')
@section('title', __('Testimonial') . ' — ' . config('app.name'))
@section('content')
<div class="mb-6 flex flex-wrap items-center justify-between gap-4">
    <h1 class="text-2xl font-bold text-gray-900">{{ __('Testimonial') }}: {{ $testimonial->testimonial_number }}</h1>
    <div class="flex gap-2">
        <a href="{{ route('dashboard.testimonials.index') }}" class="rounded-lg bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-200">{{ __('Back') }}</a>
        <a href="{{ route('dashboard.testimonials.print', $testimonial) }}" target="_blank" class="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700">{{ __('Print') }}</a>
        @can('update', $testimonial)
            <a href="{{ route('dashboard.testimonials.edit', $testimonial) }}" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700">{{ __('Edit') }}</a>
        @endcan
        @can('delete', $testimonial)
            <form method="post" action="{{ route('dashboard.testimonials.destroy', $testimonial) }}" onsubmit="return confirm('{{ __('Are you sure?') }}')">
                @csrf @method('delete')
                <button type="submit" class="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700">{{ __('Delete') }}</button>
            </form>
        @endcan
    </div>
</div>
<div class="grid gap-6 sm:grid-cols-2">
    <div class="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
        <dl class="space-y-4 text-sm">
            <div><dt class="text-gray-500">{{ __('Testimonial number') }}</dt><dd class="font-mono font-medium">{{ $testimonial->testimonial_number }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Title') }}</dt><dd class="font-medium">{{ $testimonial->name }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Student') }}</dt><dd class="font-medium">{{ $testimonial->student?->user?->name ?? 'N/A' }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Type') }}</dt><dd><span class="rounded-full bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-700">{{ __(ucfirst(str_replace('_', ' ', $testimonial->testimonial_type))) }}</span></dd></div>
            <div><dt class="text-gray-500">{{ __('Issue date') }}</dt><dd>{{ $testimonial->issue_date?->format('d M Y') }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Status') }}</dt><dd><span class="rounded-full px-2.5 py-0.5 text-xs font-medium {{ $testimonial->status === 'issued' ? 'bg-green-100 text-green-700' : ($testimonial->status === 'revoked' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700') }}">{{ __(ucfirst($testimonial->status)) }}</span></dd></div>
            <div><dt class="text-gray-500">{{ __('Given by') }}</dt><dd>{{ $testimonial->author_name ?? 'N/A' }} {{ $testimonial->author_designation ? '(' . $testimonial->author_designation . ')' : '' }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Rating') }}</dt><dd>{{ $testimonial->rating ?? 'N/A' }} {{ __('Stars') }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Generated by') }}</dt><dd>{{ $testimonial->generatedBy?->name ?? 'N/A' }}</dd></div>
            <div><dt class="text-gray-500">{{ __('Created') }}</dt><dd>{{ $testimonial->created_at?->format('d M Y H:i') }}</dd></div>
            @if(!empty($testimonial->body))
                <div class="sm:col-span-2"><dt class="text-gray-500">{{ __('Testimonial body') }}</dt><dd class="mt-1 whitespace-pre-wrap text-sm text-gray-700">{{ is_array($testimonial->body) ? implode("\n", $testimonial->body) : $testimonial->body }}</dd></div>
            @endif
            @if($testimonial->content)
                <div class="sm:col-span-2"><dt class="text-gray-500">{{ __('Additional content') }}</dt><dd class="mt-1 whitespace-pre-wrap text-sm text-gray-700">{{ $testimonial->content }}</dd></div>
            @endif
        </dl>
    </div>
</div>
@endsection
